from Bio.Seq import Seq
#ADICIONA EL FORWARD DE TU INSERTO EN 5 3 
FWD_INSERTO53 = Seq("ATGGCGGCTATGCCGG")
#ADICIONA EL REVERSE DE TU INSERTO EN 5 3
REV_INSERTO53 = Seq("GTCTTTCAGCGCCAGCAGC")
#ADICIONA EL FORWARD DE TU VECTOR EN 5 3
FWD_VETOR53 = Seq("CTCGAGTCTGGTAAAGAAAC")
#ADICIONA EL REVERSE DE TU VECTOR EN 5 3
REV_VETOR53 = Seq("CATATGTATATCTCCTTCTTATACTTAAC")
CAUDA_REV_INSERTO = FWD_VETOR53.reverse_complement()
#print(CAUDA_REV_INSERTO)
CAUDA_FWD_INSERTO = REV_VETOR53.reverse_complement()
#print(CAUDA_FWD_INSERTO)
stop = Seq("TTA")
FORWARD_GIBSON = CAUDA_FWD_INSERTO + FWD_INSERTO53
lenght_FWD_GIB = len(FORWARD_GIBSON)
REVERSE_GIBSON = CAUDA_REV_INSERTO + stop + REV_INSERTO53
lenght_REV_GIB = len(REVERSE_GIBSON)
print("FORWARD es:" + " " + FORWARD_GIBSON)
print(f'{"NUMERO DE BASES es:"}{" "}{lenght_FWD_GIB}')
print("REVERSE es:" + " " + REVERSE_GIBSON)
print(f'{"NUMERO DE BASES es:"}{" "}{lenght_REV_GIB}')